services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: backend
    volumes:
      - type: bind
        source: ./data
        target: /home/node/app/data
      - ./backend/src:/home/node/app/src
      - ./backend/nodemon.json:/home/node/app/nodemon.json
    container_name: amx
    expose:
      - '12345'
    ports:
      - '12345:12345'
    command: npm run dev
